//go:build !ignore_autogenerated

/*
Copyright 2024 Nokia.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "github.com/kuidio/kuid/apis/backend/ipam/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFDLinkParameters) DeepCopyInto(out *BFDLinkParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MinTx != nil {
		in, out := &in.MinTx, &out.MinTx
		*out = new(uint32)
		**out = **in
	}
	if in.MinRx != nil {
		in, out := &in.MinRx, &out.MinRx
		*out = new(uint32)
		**out = **in
	}
	if in.MinEchoRx != nil {
		in, out := &in.MinEchoRx, &out.MinEchoRx
		*out = new(uint32)
		**out = **in
	}
	if in.Multiplier != nil {
		in, out := &in.Multiplier, &out.Multiplier
		*out = new(uint32)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFDLinkParameters.
func (in *BFDLinkParameters) DeepCopy() *BFDLinkParameters {
	if in == nil {
		return nil
	}
	out := new(BFDLinkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPLinkParameters) DeepCopyInto(out *BGPLinkParameters) {
	*out = *in
	if in.BFD != nil {
		in, out := &in.BFD, &out.BFD
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPLinkParameters.
func (in *BGPLinkParameters) DeepCopy() *BGPLinkParameters {
	if in == nil {
		return nil
	}
	out := new(BGPLinkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IGPLinkParameters) DeepCopyInto(out *IGPLinkParameters) {
	*out = *in
	if in.NetworkType != nil {
		in, out := &in.NetworkType, &out.NetworkType
		*out = new(NetworkType)
		**out = **in
	}
	if in.Passive != nil {
		in, out := &in.Passive, &out.Passive
		*out = new(bool)
		**out = **in
	}
	if in.BFD != nil {
		in, out := &in.BFD, &out.BFD
		*out = new(bool)
		**out = **in
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IGPLinkParameters.
func (in *IGPLinkParameters) DeepCopy() *IGPLinkParameters {
	if in == nil {
		return nil
	}
	out := new(IGPLinkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISISLinkParameters) DeepCopyInto(out *ISISLinkParameters) {
	*out = *in
	in.IGPLinkParameters.DeepCopyInto(&out.IGPLinkParameters)
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(ISISLevel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISISLinkParameters.
func (in *ISISLinkParameters) DeepCopy() *ISISLinkParameters {
	if in == nil {
		return nil
	}
	out := new(ISISLinkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesign) DeepCopyInto(out *NetworkDesign) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesign.
func (in *NetworkDesign) DeepCopy() *NetworkDesign {
	if in == nil {
		return nil
	}
	out := new(NetworkDesign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkDesign) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulation) DeepCopyInto(out *NetworkDesignEncapsulation) {
	*out = *in
	if in.VXLAN != nil {
		in, out := &in.VXLAN, &out.VXLAN
		*out = new(NetworkDesignEncapsulationVXLAN)
		**out = **in
	}
	if in.MPLS != nil {
		in, out := &in.MPLS, &out.MPLS
		*out = new(NetworkDesignEncapsulationMPLS)
		(*in).DeepCopyInto(*out)
	}
	if in.SRV6 != nil {
		in, out := &in.SRV6, &out.SRV6
		*out = new(NetworkDesignEncapsulationSRv6)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulation.
func (in *NetworkDesignEncapsulation) DeepCopy() *NetworkDesignEncapsulation {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLS) DeepCopyInto(out *NetworkDesignEncapsulationMPLS) {
	*out = *in
	if in.LDP != nil {
		in, out := &in.LDP, &out.LDP
		*out = new(NetworkDesignEncapsulationMPLSLDP)
		**out = **in
	}
	if in.SR != nil {
		in, out := &in.SR, &out.SR
		*out = new(NetworkDesignEncapsulationMPLSSR)
		**out = **in
	}
	if in.RSVP != nil {
		in, out := &in.RSVP, &out.RSVP
		*out = new(NetworkDesignEncapsulationMPLSRSVP)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLS.
func (in *NetworkDesignEncapsulationMPLS) DeepCopy() *NetworkDesignEncapsulationMPLS {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLSLDP) DeepCopyInto(out *NetworkDesignEncapsulationMPLSLDP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLSLDP.
func (in *NetworkDesignEncapsulationMPLSLDP) DeepCopy() *NetworkDesignEncapsulationMPLSLDP {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLSLDP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLSRSVP) DeepCopyInto(out *NetworkDesignEncapsulationMPLSRSVP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLSRSVP.
func (in *NetworkDesignEncapsulationMPLSRSVP) DeepCopy() *NetworkDesignEncapsulationMPLSRSVP {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLSRSVP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLSSR) DeepCopyInto(out *NetworkDesignEncapsulationMPLSSR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLSSR.
func (in *NetworkDesignEncapsulationMPLSSR) DeepCopy() *NetworkDesignEncapsulationMPLSSR {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLSSR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLSSRv6MicroSID) DeepCopyInto(out *NetworkDesignEncapsulationMPLSSRv6MicroSID) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLSSRv6MicroSID.
func (in *NetworkDesignEncapsulationMPLSSRv6MicroSID) DeepCopy() *NetworkDesignEncapsulationMPLSSRv6MicroSID {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLSSRv6MicroSID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationSRv6) DeepCopyInto(out *NetworkDesignEncapsulationSRv6) {
	*out = *in
	if in.MicroSID != nil {
		in, out := &in.MicroSID, &out.MicroSID
		*out = new(NetworkDesignEncapsulationMPLSSRv6MicroSID)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationSRv6.
func (in *NetworkDesignEncapsulationSRv6) DeepCopy() *NetworkDesignEncapsulationSRv6 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationSRv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationVXLAN) DeepCopyInto(out *NetworkDesignEncapsulationVXLAN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationVXLAN.
func (in *NetworkDesignEncapsulationVXLAN) DeepCopy() *NetworkDesignEncapsulationVXLAN {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationVXLAN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignInterfaceParameters) DeepCopyInto(out *NetworkDesignInterfaceParameters) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]ipamv1alpha1.Prefix, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignInterfaceParameters.
func (in *NetworkDesignInterfaceParameters) DeepCopy() *NetworkDesignInterfaceParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignInterfaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignInterfaces) DeepCopyInto(out *NetworkDesignInterfaces) {
	*out = *in
	if in.Loopback != nil {
		in, out := &in.Loopback, &out.Loopback
		*out = new(NetworkDesignInterfacesLoopback)
		(*in).DeepCopyInto(*out)
	}
	if in.Underlay != nil {
		in, out := &in.Underlay, &out.Underlay
		*out = new(NetworkDesignInterfacesUnderlay)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignInterfaces.
func (in *NetworkDesignInterfaces) DeepCopy() *NetworkDesignInterfaces {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignInterfaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignInterfacesLoopback) DeepCopyInto(out *NetworkDesignInterfacesLoopback) {
	*out = *in
	in.NetworkDesignInterfaceParameters.DeepCopyInto(&out.NetworkDesignInterfaceParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignInterfacesLoopback.
func (in *NetworkDesignInterfacesLoopback) DeepCopy() *NetworkDesignInterfacesLoopback {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignInterfacesLoopback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignInterfacesUnderlay) DeepCopyInto(out *NetworkDesignInterfacesUnderlay) {
	*out = *in
	in.NetworkDesignInterfaceParameters.DeepCopyInto(&out.NetworkDesignInterfaceParameters)
	if in.BFD != nil {
		in, out := &in.BFD, &out.BFD
		*out = new(BFDLinkParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignInterfacesUnderlay.
func (in *NetworkDesignInterfacesUnderlay) DeepCopy() *NetworkDesignInterfacesUnderlay {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignInterfacesUnderlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignList) DeepCopyInto(out *NetworkDesignList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkDesign, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignList.
func (in *NetworkDesignList) DeepCopy() *NetworkDesignList {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkDesignList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocols) DeepCopyInto(out *NetworkDesignProtocols) {
	*out = *in
	if in.OSPF != nil {
		in, out := &in.OSPF, &out.OSPF
		*out = new(NetworkDesignProtocolsOSPF)
		(*in).DeepCopyInto(*out)
	}
	if in.ISIS != nil {
		in, out := &in.ISIS, &out.ISIS
		*out = new(NetworkDesignProtocolsISIS)
		(*in).DeepCopyInto(*out)
	}
	if in.IBGP != nil {
		in, out := &in.IBGP, &out.IBGP
		*out = new(NetworkDesignProtocolsIBGP)
		(*in).DeepCopyInto(*out)
	}
	if in.EBGP != nil {
		in, out := &in.EBGP, &out.EBGP
		*out = new(NetworkDesignProtocolsEBGP)
		(*in).DeepCopyInto(*out)
	}
	if in.BGPEVPN != nil {
		in, out := &in.BGPEVPN, &out.BGPEVPN
		*out = new(NetworkDesignProtocolsBGPEVPN)
		**out = **in
	}
	if in.BGPVPNv4 != nil {
		in, out := &in.BGPVPNv4, &out.BGPVPNv4
		*out = new(NetworkDesignProtocolsBGPVPNv4)
		**out = **in
	}
	if in.BGPVPNv6 != nil {
		in, out := &in.BGPVPNv6, &out.BGPVPNv6
		*out = new(NetworkDesignProtocolsBGPVPNv6)
		**out = **in
	}
	if in.BGPRouteTarget != nil {
		in, out := &in.BGPRouteTarget, &out.BGPRouteTarget
		*out = new(NetworkDesignProtocolsBGPRouteTarget)
		**out = **in
	}
	if in.BGPLabeledUnicastv4 != nil {
		in, out := &in.BGPLabeledUnicastv4, &out.BGPLabeledUnicastv4
		*out = new(NetworkDesignProtocolsBGPLabeledUnicastv4)
		**out = **in
	}
	if in.BGPLabeledUnicastv6 != nil {
		in, out := &in.BGPLabeledUnicastv6, &out.BGPLabeledUnicastv6
		*out = new(NetworkDesignProtocolsBGPLabeledUnicastv6)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocols.
func (in *NetworkDesignProtocols) DeepCopy() *NetworkDesignProtocols {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocols)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPEVPN) DeepCopyInto(out *NetworkDesignProtocolsBGPEVPN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPEVPN.
func (in *NetworkDesignProtocolsBGPEVPN) DeepCopy() *NetworkDesignProtocolsBGPEVPN {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPEVPN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPLabeledUnicastv4) DeepCopyInto(out *NetworkDesignProtocolsBGPLabeledUnicastv4) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPLabeledUnicastv4.
func (in *NetworkDesignProtocolsBGPLabeledUnicastv4) DeepCopy() *NetworkDesignProtocolsBGPLabeledUnicastv4 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPLabeledUnicastv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPLabeledUnicastv6) DeepCopyInto(out *NetworkDesignProtocolsBGPLabeledUnicastv6) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPLabeledUnicastv6.
func (in *NetworkDesignProtocolsBGPLabeledUnicastv6) DeepCopy() *NetworkDesignProtocolsBGPLabeledUnicastv6 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPLabeledUnicastv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPRouteTarget) DeepCopyInto(out *NetworkDesignProtocolsBGPRouteTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPRouteTarget.
func (in *NetworkDesignProtocolsBGPRouteTarget) DeepCopy() *NetworkDesignProtocolsBGPRouteTarget {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPRouteTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPVPNv4) DeepCopyInto(out *NetworkDesignProtocolsBGPVPNv4) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPVPNv4.
func (in *NetworkDesignProtocolsBGPVPNv4) DeepCopy() *NetworkDesignProtocolsBGPVPNv4 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPVPNv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPVPNv6) DeepCopyInto(out *NetworkDesignProtocolsBGPVPNv6) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPVPNv6.
func (in *NetworkDesignProtocolsBGPVPNv6) DeepCopy() *NetworkDesignProtocolsBGPVPNv6 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPVPNv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsEBGP) DeepCopyInto(out *NetworkDesignProtocolsEBGP) {
	*out = *in
	if in.ASPool != nil {
		in, out := &in.ASPool, &out.ASPool
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsEBGP.
func (in *NetworkDesignProtocolsEBGP) DeepCopy() *NetworkDesignProtocolsEBGP {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsEBGP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsIBGP) DeepCopyInto(out *NetworkDesignProtocolsIBGP) {
	*out = *in
	if in.AS != nil {
		in, out := &in.AS, &out.AS
		*out = new(uint32)
		**out = **in
	}
	if in.RouteReflectors != nil {
		in, out := &in.RouteReflectors, &out.RouteReflectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsIBGP.
func (in *NetworkDesignProtocolsIBGP) DeepCopy() *NetworkDesignProtocolsIBGP {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsIBGP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsISIS) DeepCopyInto(out *NetworkDesignProtocolsISIS) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(string)
		**out = **in
	}
	if in.Areas != nil {
		in, out := &in.Areas, &out.Areas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxECMPPaths != nil {
		in, out := &in.MaxECMPPaths, &out.MaxECMPPaths
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsISIS.
func (in *NetworkDesignProtocolsISIS) DeepCopy() *NetworkDesignProtocolsISIS {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsISIS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsOSPF) DeepCopyInto(out *NetworkDesignProtocolsOSPF) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(string)
		**out = **in
	}
	if in.MaxECMPPaths != nil {
		in, out := &in.MaxECMPPaths, &out.MaxECMPPaths
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsOSPF.
func (in *NetworkDesignProtocolsOSPF) DeepCopy() *NetworkDesignProtocolsOSPF {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsOSPF)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignSpec) DeepCopyInto(out *NetworkDesignSpec) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = new(NetworkDesignInterfaces)
		(*in).DeepCopyInto(*out)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = new(NetworkDesignProtocols)
		(*in).DeepCopyInto(*out)
	}
	if in.Encapsultation != nil {
		in, out := &in.Encapsultation, &out.Encapsultation
		*out = new(NetworkDesignEncapsulation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignSpec.
func (in *NetworkDesignSpec) DeepCopy() *NetworkDesignSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignStatus) DeepCopyInto(out *NetworkDesignStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignStatus.
func (in *NetworkDesignStatus) DeepCopy() *NetworkDesignStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSPFLinkParameters) DeepCopyInto(out *OSPFLinkParameters) {
	*out = *in
	in.IGPLinkParameters.DeepCopyInto(&out.IGPLinkParameters)
	if in.Area != nil {
		in, out := &in.Area, &out.Area
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSPFLinkParameters.
func (in *OSPFLinkParameters) DeepCopy() *OSPFLinkParameters {
	if in == nil {
		return nil
	}
	out := new(OSPFLinkParameters)
	in.DeepCopyInto(out)
	return out
}
