/*
Copyright 2024 Nokia.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/kubenet-dev/apis/apis/topo/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"
	v1alpha1 "github.com/kubenet-dev/apis/apis/network/core/v1alpha1"
	v1alpha12 "github.com/kuidio/kuid/apis/infra/v1alpha1"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *Topology) Reset()      { *m = Topology{} }
func (*Topology) ProtoMessage() {}
func (*Topology) Descriptor() ([]byte, []int) {
	return fileDescriptor_978428ce7eab36fb, []int{0}
}
func (m *Topology) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Topology) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Topology) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topology.Merge(m, src)
}
func (m *Topology) XXX_Size() int {
	return m.Size()
}
func (m *Topology) XXX_DiscardUnknown() {
	xxx_messageInfo_Topology.DiscardUnknown(m)
}

var xxx_messageInfo_Topology proto.InternalMessageInfo

func (m *TopologyEndpoint) Reset()      { *m = TopologyEndpoint{} }
func (*TopologyEndpoint) ProtoMessage() {}
func (*TopologyEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_978428ce7eab36fb, []int{1}
}
func (m *TopologyEndpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TopologyEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TopologyEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyEndpoint.Merge(m, src)
}
func (m *TopologyEndpoint) XXX_Size() int {
	return m.Size()
}
func (m *TopologyEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyEndpoint proto.InternalMessageInfo

func (m *TopologyLink) Reset()      { *m = TopologyLink{} }
func (*TopologyLink) ProtoMessage() {}
func (*TopologyLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_978428ce7eab36fb, []int{2}
}
func (m *TopologyLink) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TopologyLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TopologyLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyLink.Merge(m, src)
}
func (m *TopologyLink) XXX_Size() int {
	return m.Size()
}
func (m *TopologyLink) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyLink.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyLink proto.InternalMessageInfo

func (m *TopologyList) Reset()      { *m = TopologyList{} }
func (*TopologyList) ProtoMessage() {}
func (*TopologyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_978428ce7eab36fb, []int{3}
}
func (m *TopologyList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TopologyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TopologyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyList.Merge(m, src)
}
func (m *TopologyList) XXX_Size() int {
	return m.Size()
}
func (m *TopologyList) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyList.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyList proto.InternalMessageInfo

func (m *TopologyNode) Reset()      { *m = TopologyNode{} }
func (*TopologyNode) ProtoMessage() {}
func (*TopologyNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_978428ce7eab36fb, []int{4}
}
func (m *TopologyNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TopologyNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TopologyNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyNode.Merge(m, src)
}
func (m *TopologyNode) XXX_Size() int {
	return m.Size()
}
func (m *TopologyNode) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyNode.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyNode proto.InternalMessageInfo

func (m *TopologySpec) Reset()      { *m = TopologySpec{} }
func (*TopologySpec) ProtoMessage() {}
func (*TopologySpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_978428ce7eab36fb, []int{5}
}
func (m *TopologySpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TopologySpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TopologySpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologySpec.Merge(m, src)
}
func (m *TopologySpec) XXX_Size() int {
	return m.Size()
}
func (m *TopologySpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologySpec.DiscardUnknown(m)
}

var xxx_messageInfo_TopologySpec proto.InternalMessageInfo

func (m *TopologyStatus) Reset()      { *m = TopologyStatus{} }
func (*TopologyStatus) ProtoMessage() {}
func (*TopologyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_978428ce7eab36fb, []int{6}
}
func (m *TopologyStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TopologyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TopologyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyStatus.Merge(m, src)
}
func (m *TopologyStatus) XXX_Size() int {
	return m.Size()
}
func (m *TopologyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyStatus proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Topology)(nil), "github.com.kubenet_dev.apis.apis.topo.v1alpha1.Topology")
	proto.RegisterType((*TopologyEndpoint)(nil), "github.com.kubenet_dev.apis.apis.topo.v1alpha1.TopologyEndpoint")
	proto.RegisterType((*TopologyLink)(nil), "github.com.kubenet_dev.apis.apis.topo.v1alpha1.TopologyLink")
	proto.RegisterType((*TopologyList)(nil), "github.com.kubenet_dev.apis.apis.topo.v1alpha1.TopologyList")
	proto.RegisterType((*TopologyNode)(nil), "github.com.kubenet_dev.apis.apis.topo.v1alpha1.TopologyNode")
	proto.RegisterType((*TopologySpec)(nil), "github.com.kubenet_dev.apis.apis.topo.v1alpha1.TopologySpec")
	proto.RegisterType((*TopologyStatus)(nil), "github.com.kubenet_dev.apis.apis.topo.v1alpha1.TopologyStatus")
}

func init() {
	proto.RegisterFile("github.com/kubenet-dev/apis/apis/topo/v1alpha1/generated.proto", fileDescriptor_978428ce7eab36fb)
}

var fileDescriptor_978428ce7eab36fb = []byte{
	// 1071 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0x26, 0x6e, 0x62, 0x4f, 0x9c, 0x92, 0xcc, 0x69, 0x89, 0x90, 0x13, 0x59, 0x42, 0x0a,
	0x82, 0xae, 0x49, 0x14, 0xa1, 0x0a, 0x50, 0x05, 0xdb, 0x90, 0x2a, 0x28, 0x6d, 0xad, 0x49, 0xe0,
	0x80, 0xa0, 0x30, 0xde, 0x1d, 0xdb, 0x83, 0xbd, 0x3b, 0xcb, 0xcc, 0xd8, 0x28, 0xb7, 0xde, 0x38,
	0xc2, 0x57, 0x80, 0x0b, 0x5f, 0x80, 0x0f, 0x11, 0x89, 0x4b, 0x8f, 0x3d, 0x59, 0xc4, 0x7c, 0x11,
	0x34, 0x6f, 0x66, 0xbd, 0x4e, 0xdc, 0xa4, 0xd4, 0xb9, 0xd8, 0x3b, 0xef, 0xcf, 0xef, 0xf7, 0xde,
	0xdb, 0xf7, 0xe6, 0x2d, 0x7a, 0xd0, 0xe1, 0xba, 0x3b, 0x68, 0x05, 0x91, 0x48, 0x1a, 0xbd, 0x41,
	0x8b, 0xa5, 0x4c, 0xdf, 0x8b, 0xd9, 0xb0, 0x41, 0x33, 0xae, 0xec, 0x8f, 0x16, 0x99, 0x68, 0x0c,
	0x77, 0x69, 0x3f, 0xeb, 0xd2, 0xdd, 0x46, 0x87, 0xa5, 0x4c, 0x52, 0xcd, 0xe2, 0x20, 0x93, 0x42,
	0x0b, 0x1c, 0x14, 0xfe, 0x81, 0xf3, 0xff, 0x3e, 0x66, 0xc3, 0xc0, 0xb8, 0xda, 0x1f, 0xe3, 0x1f,
	0xe4, 0xfe, 0x9b, 0xf7, 0xa6, 0xf8, 0x3a, 0xa2, 0x23, 0x1a, 0x00, 0xd3, 0x1a, 0xb4, 0xe1, 0x04,
	0x07, 0x78, 0xb2, 0xf0, 0x9b, 0x0f, 0xa7, 0xc3, 0x6b, 0x0b, 0x99, 0x40, 0x70, 0x51, 0x57, 0x48,
	0x26, 0x6c, 0x78, 0x91, 0x48, 0x63, 0xae, 0xb9, 0x48, 0xaf, 0x8d, 0x71, 0xf3, 0xf0, 0xb5, 0x39,
	0xa6, 0x4c, 0xff, 0x2c, 0x64, 0xaf, 0x11, 0x09, 0xc9, 0xae, 0xc7, 0xf9, 0xe4, 0x12, 0x0e, 0x8f,
	0xb9, 0x80, 0xbf, 0x3c, 0x8e, 0x24, 0xb9, 0x29, 0x88, 0x8f, 0x6f, 0x72, 0xe6, 0x69, 0x5b, 0xd2,
	0xeb, 0x7d, 0xf7, 0x7b, 0xf7, 0x55, 0xc0, 0x21, 0xe1, 0x84, 0x46, 0x5d, 0x9e, 0x32, 0x79, 0xd6,
	0xc8, 0x7a, 0x1d, 0xeb, 0x9c, 0x30, 0x6d, 0x7c, 0x67, 0xbc, 0x3e, 0xba, 0xce, 0x4b, 0x0e, 0x52,
	0xcd, 0x13, 0xd6, 0x50, 0x51, 0x97, 0x25, 0xf4, 0xaa, 0x5f, 0xfd, 0xaf, 0x45, 0x54, 0x3e, 0x15,
	0x99, 0xe8, 0x8b, 0xce, 0x19, 0xfe, 0x01, 0x95, 0x0d, 0x7e, 0x4c, 0x35, 0xf5, 0xbd, 0x6d, 0x6f,
	0x67, 0x75, 0xef, 0xc3, 0xc0, 0xe2, 0x06, 0xd3, 0xb8, 0x41, 0xd6, 0xeb, 0xd8, 0xd7, 0x6d, 0xac,
	0x83, 0xe1, 0x6e, 0xf0, 0xb4, 0xf5, 0x23, 0x8b, 0xf4, 0x63, 0xa6, 0x69, 0x88, 0xcf, 0x47, 0x5b,
	0x0b, 0xe3, 0xd1, 0x16, 0x2a, 0x64, 0x64, 0x82, 0x8a, 0x9f, 0xa1, 0x92, 0xca, 0x58, 0xe4, 0x2f,
	0x02, 0xfa, 0xa7, 0x6f, 0xd8, 0x50, 0x41, 0x1e, 0xe9, 0x49, 0xc6, 0xa2, 0xb0, 0xea, 0x98, 0x4a,
	0xe6, 0x44, 0x00, 0x17, 0xb7, 0xd1, 0xb2, 0xd2, 0x54, 0x0f, 0x94, 0xbf, 0x04, 0x0c, 0x0f, 0xe6,
	0x66, 0x00, 0x94, 0xf0, 0xae, 0xe3, 0x58, 0xb6, 0x67, 0xe2, 0xd0, 0xeb, 0xcf, 0x17, 0xd1, 0x7a,
	0x6e, 0xfa, 0x45, 0x1a, 0x67, 0x82, 0xa7, 0x1a, 0x6f, 0xa3, 0x52, 0x2a, 0x62, 0x06, 0xa5, 0xab,
	0x14, 0xe1, 0x3d, 0x11, 0x31, 0x23, 0xa0, 0xc1, 0xef, 0xa3, 0x4a, 0x22, 0xe2, 0x41, 0x9f, 0x85,
	0xf4, 0x0c, 0x6a, 0xb0, 0x16, 0xae, 0x8d, 0x47, 0x5b, 0x95, 0xc7, 0xb9, 0x90, 0x14, 0x7a, 0x5c,
	0x47, 0xcb, 0xf6, 0x00, 0xb9, 0xac, 0x85, 0xc8, 0xc4, 0x61, 0x2d, 0x89, 0xd3, 0x18, 0xca, 0x4c,
	0x48, 0xed, 0x97, 0xc0, 0x62, 0x42, 0xd9, 0x14, 0x52, 0x13, 0xd0, 0xe0, 0xf7, 0xd0, 0x0a, 0x8d,
	0x69, 0xa6, 0x85, 0xf4, 0xef, 0x40, 0x5c, 0x6f, 0x39, 0xa3, 0x95, 0xcf, 0xad, 0x98, 0xe4, 0x7a,
	0xfc, 0x01, 0x2a, 0x33, 0x97, 0x8b, 0xbf, 0x0c, 0x80, 0xeb, 0xce, 0xb6, 0x9c, 0xe7, 0x48, 0x26,
	0x16, 0xf5, 0xdf, 0x4b, 0xa8, 0x9a, 0x97, 0xe0, 0x98, 0xa7, 0x3d, 0xfc, 0x13, 0xaa, 0xe4, 0x4a,
	0xe5, 0x7b, 0xdb, 0x4b, 0x3b, 0xab, 0x7b, 0x9f, 0xcd, 0x5b, 0xfe, 0x9c, 0x2f, 0xdc, 0x70, 0x11,
	0x54, 0x72, 0x89, 0x22, 0x05, 0x0b, 0x8e, 0xd1, 0x52, 0xab, 0x1d, 0xbb, 0x6e, 0x3a, 0x7a, 0x3d,
	0x99, 0x1b, 0xfd, 0xc0, 0x8c, 0x7e, 0x41, 0x1a, 0x1e, 0x1e, 0x98, 0x04, 0x9a, 0x54, 0xd2, 0x84,
	0x69, 0x26, 0x55, 0xb8, 0x32, 0x1e, 0x6d, 0x2d, 0x85, 0x87, 0x07, 0xc4, 0xc0, 0x03, 0x4b, 0x27,
	0x73, 0x1d, 0x35, 0x3f, 0xcb, 0xa3, 0xe6, 0x2b, 0x59, 0x1e, 0x35, 0x89, 0x81, 0xc7, 0x5d, 0x54,
	0x12, 0x2a, 0x6b, 0xc3, 0xab, 0x5c, 0xdd, 0xfb, 0x72, 0x5e, 0x9a, 0xa7, 0x27, 0xcd, 0xc3, 0x2b,
	0x3c, 0x65, 0xd3, 0x12, 0x46, 0x4e, 0x80, 0xc1, 0x30, 0x71, 0xc5, 0x15, 0xf4, 0xc3, 0x2d, 0x98,
	0x8e, 0x4e, 0x8e, 0x4e, 0x5e, 0xc5, 0x64, 0xe4, 0x04, 0x18, 0xea, 0x7f, 0x7b, 0xd3, 0x3d, 0xa2,
	0x34, 0xfe, 0x76, 0xe6, 0x86, 0x09, 0xfe, 0xdf, 0x0d, 0x63, 0xbc, 0xe1, 0x7e, 0x99, 0xb4, 0x64,
	0x2e, 0x99, 0xba, 0x5d, 0xbe, 0x43, 0x77, 0xb8, 0x66, 0x89, 0xf2, 0x17, 0xa1, 0xfb, 0xee, 0xcf,
	0xdb, 0x7d, 0xe1, 0x9a, 0x23, 0xb9, 0x73, 0x64, 0xe0, 0x88, 0x45, 0xad, 0xff, 0x39, 0xd5, 0xf1,
	0x66, 0xa8, 0xf1, 0x3b, 0xa8, 0x94, 0xd2, 0x24, 0x1f, 0x78, 0x48, 0xfe, 0x09, 0x4d, 0xcc, 0xb0,
	0xd3, 0x84, 0x99, 0xf9, 0x95, 0xac, 0xc3, 0x45, 0x0a, 0xfd, 0x59, 0xb1, 0xf3, 0x4b, 0x40, 0x42,
	0x9c, 0xc6, 0x20, 0x28, 0xae, 0xed, 0x84, 0x3b, 0x84, 0x13, 0xae, 0x19, 0x01, 0xa9, 0xd1, 0x4a,
	0x1a, 0xf5, 0xa0, 0x25, 0x9c, 0x96, 0xd0, 0xa8, 0x47, 0x40, 0x8a, 0x77, 0x50, 0x39, 0x13, 0x0a,
	0xd6, 0xa1, 0x1b, 0xed, 0xaa, 0xa9, 0x4b, 0xd3, 0xc9, 0xc8, 0x44, 0x8b, 0x7f, 0xf1, 0xd0, 0xc6,
	0x40, 0x31, 0x79, 0xc0, 0xda, 0x3c, 0x65, 0xf1, 0x31, 0x6d, 0xb1, 0xbe, 0x82, 0x11, 0x9f, 0xb9,
	0x21, 0xcd, 0xae, 0x82, 0x3f, 0x5b, 0x1f, 0xbb, 0xe8, 0x8a, 0x0a, 0x7d, 0x75, 0x15, 0x25, 0x7c,
	0xdb, 0x95, 0x6a, 0x63, 0x46, 0x45, 0x66, 0x39, 0xf1, 0x33, 0x54, 0xee, 0x8b, 0x88, 0x42, 0xcc,
	0x2b, 0xc0, 0xbf, 0x7f, 0x23, 0x3f, 0xec, 0xca, 0x82, 0xfe, 0xd8, 0xf9, 0xda, 0x4c, 0xf3, 0x13,
	0x99, 0x60, 0x42, 0x4d, 0xa4, 0x18, 0xf2, 0x98, 0x49, 0xbf, 0x3c, 0x55, 0x13, 0x27, 0x23, 0x13,
	0x2d, 0xde, 0x47, 0xd5, 0xac, 0x4f, 0xb5, 0xf9, 0xcc, 0x38, 0x3d, 0xcb, 0x98, 0x5f, 0x01, 0xeb,
	0xf5, 0xf1, 0x68, 0xab, 0xda, 0x9c, 0x92, 0x93, 0x4b, 0x56, 0xf8, 0x5d, 0xb4, 0x32, 0x64, 0x52,
	0x99, 0xf0, 0x11, 0x38, 0xac, 0x9a, 0x9b, 0xf4, 0x6b, 0x2b, 0x22, 0xb9, 0xce, 0x6c, 0xd5, 0xea,
	0xf4, 0xae, 0xc2, 0x6d, 0x54, 0x8e, 0x59, 0x9b, 0x0e, 0xfa, 0x70, 0x35, 0xde, 0x6a, 0xf7, 0x99,
	0xce, 0xb3, 0x59, 0x1d, 0x38, 0x44, 0x32, 0xc1, 0x36, 0x13, 0x60, 0x16, 0x4d, 0x3e, 0x01, 0xb7,
	0x23, 0xa9, 0x98, 0x09, 0x30, 0x4f, 0x8a, 0x58, 0x54, 0x03, 0xdf, 0xe7, 0x69, 0xcf, 0x6c, 0xd7,
	0x5b, 0xc1, 0x9b, 0x6b, 0xc3, 0xc2, 0x9b, 0x27, 0x45, 0x2c, 0x6a, 0xfd, 0x0f, 0x0f, 0xdd, 0xbd,
	0xbc, 0x80, 0xf1, 0xaf, 0x1e, 0xda, 0x98, 0x7c, 0xf5, 0xb1, 0xd8, 0x4a, 0x5d, 0x09, 0x0f, 0x2f,
	0xd1, 0x9b, 0x77, 0x04, 0xe4, 0xf6, 0x83, 0x31, 0xef, 0x5f, 0xe7, 0x5a, 0xc4, 0xf0, 0xf0, 0x2a,
	0x5a, 0xd1, 0xc2, 0x33, 0x2a, 0x32, 0xcb, 0x1d, 0x9e, 0x9e, 0x5f, 0xd4, 0x16, 0x5e, 0x5c, 0xd4,
	0x16, 0x5e, 0x5e, 0xd4, 0x16, 0x9e, 0x8f, 0x6b, 0xde, 0xf9, 0xb8, 0xe6, 0xbd, 0x18, 0xd7, 0xbc,
	0x97, 0xe3, 0x9a, 0xf7, 0xcf, 0xb8, 0xe6, 0xfd, 0xf6, 0x6f, 0x6d, 0xe1, 0x9b, 0xe0, 0xcd, 0x3e,
	0xb5, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x4a, 0x84, 0x15, 0x9b, 0x0b, 0x00, 0x00,
}

func (m *Topology) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Topology) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Topology) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TopologyEndpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TopologyEndpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TopologyEndpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintGenerated(dAtA, i, uint64(m.Endpoint))
	i--
	dAtA[i] = 0x30
	i -= len(m.Adaptor)
	copy(dAtA[i:], m.Adaptor)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Adaptor)))
	i--
	dAtA[i] = 0x2a
	i = encodeVarintGenerated(dAtA, i, uint64(m.Port))
	i--
	dAtA[i] = 0x20
	if m.Module != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.Module))
		i--
		dAtA[i] = 0x18
	}
	if m.ModuleBay != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.ModuleBay))
		i--
		dAtA[i] = 0x10
	}
	i -= len(m.Node)
	copy(dAtA[i:], m.Node)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Node)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TopologyLink) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TopologyLink) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TopologyLink) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ISIS != nil {
		{
			size, err := m.ISIS.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.OSPF != nil {
		{
			size, err := m.OSPF.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.BGP != nil {
		{
			size, err := m.BGP.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.BFD != nil {
		{
			size, err := m.BFD.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Endpoints) > 0 {
		for iNdEx := len(m.Endpoints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Endpoints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *TopologyList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TopologyList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TopologyList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TopologyNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TopologyNode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TopologyNode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version != nil {
		i -= len(*m.Version)
		copy(dAtA[i:], *m.Version)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Version)))
		i--
		dAtA[i] = 0x52
	}
	if m.PlatformType != nil {
		i -= len(*m.PlatformType)
		copy(dAtA[i:], *m.PlatformType)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.PlatformType)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Provider != nil {
		i -= len(*m.Provider)
		copy(dAtA[i:], *m.Provider)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Provider)))
		i--
		dAtA[i] = 0x42
	}
	if m.Location != nil {
		{
			size, err := m.Location.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	{
		size, err := m.UserDefinedLabels.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.Position != nil {
		i -= len(*m.Position)
		copy(dAtA[i:], *m.Position)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Position)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Rack != nil {
		i -= len(*m.Rack)
		copy(dAtA[i:], *m.Rack)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Rack)))
		i--
		dAtA[i] = 0x22
	}
	if m.Site != nil {
		i -= len(*m.Site)
		copy(dAtA[i:], *m.Site)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Site)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Region != nil {
		i -= len(*m.Region)
		copy(dAtA[i:], *m.Region)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Region)))
		i--
		dAtA[i] = 0x12
	}
	if m.Name != nil {
		i -= len(*m.Name)
		copy(dAtA[i:], *m.Name)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TopologySpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TopologySpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TopologySpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Links) > 0 {
		for iNdEx := len(m.Links) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Links[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Nodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Defaults != nil {
		{
			size, err := m.Defaults.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TopologyStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TopologyStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TopologyStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ConditionedStatus.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Topology) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *TopologyEndpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Node)
	n += 1 + l + sovGenerated(uint64(l))
	if m.ModuleBay != nil {
		n += 1 + sovGenerated(uint64(*m.ModuleBay))
	}
	if m.Module != nil {
		n += 1 + sovGenerated(uint64(*m.Module))
	}
	n += 1 + sovGenerated(uint64(m.Port))
	l = len(m.Adaptor)
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.Endpoint))
	return n
}

func (m *TopologyLink) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Endpoints) > 0 {
		for _, e := range m.Endpoints {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if m.BFD != nil {
		l = m.BFD.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.BGP != nil {
		l = m.BGP.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.OSPF != nil {
		l = m.OSPF.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.ISIS != nil {
		l = m.ISIS.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *TopologyList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *TopologyNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Name != nil {
		l = len(*m.Name)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Region != nil {
		l = len(*m.Region)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Site != nil {
		l = len(*m.Site)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Rack != nil {
		l = len(*m.Rack)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Position != nil {
		l = len(*m.Position)
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = m.UserDefinedLabels.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if m.Location != nil {
		l = m.Location.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Provider != nil {
		l = len(*m.Provider)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.PlatformType != nil {
		l = len(*m.PlatformType)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Version != nil {
		l = len(*m.Version)
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *TopologySpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Defaults != nil {
		l = m.Defaults.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.Links) > 0 {
		for _, e := range m.Links {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *TopologyStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ConditionedStatus.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Topology) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Topology{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "TopologySpec", "TopologySpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "TopologyStatus", "TopologyStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TopologyEndpoint) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TopologyEndpoint{`,
		`Node:` + fmt.Sprintf("%v", this.Node) + `,`,
		`ModuleBay:` + valueToStringGenerated(this.ModuleBay) + `,`,
		`Module:` + valueToStringGenerated(this.Module) + `,`,
		`Port:` + fmt.Sprintf("%v", this.Port) + `,`,
		`Adaptor:` + fmt.Sprintf("%v", this.Adaptor) + `,`,
		`Endpoint:` + fmt.Sprintf("%v", this.Endpoint) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TopologyLink) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForEndpoints := "[]TopologyEndpoint{"
	for _, f := range this.Endpoints {
		repeatedStringForEndpoints += strings.Replace(strings.Replace(f.String(), "TopologyEndpoint", "TopologyEndpoint", 1), `&`, ``, 1) + ","
	}
	repeatedStringForEndpoints += "}"
	s := strings.Join([]string{`&TopologyLink{`,
		`Endpoints:` + repeatedStringForEndpoints + `,`,
		`BFD:` + strings.Replace(fmt.Sprintf("%v", this.BFD), "BFDLinkParameters", "v1alpha1.BFDLinkParameters", 1) + `,`,
		`BGP:` + strings.Replace(fmt.Sprintf("%v", this.BGP), "BGPLinkParameters", "v1alpha1.BGPLinkParameters", 1) + `,`,
		`OSPF:` + strings.Replace(fmt.Sprintf("%v", this.OSPF), "OSPFLinkParameters", "v1alpha1.OSPFLinkParameters", 1) + `,`,
		`ISIS:` + strings.Replace(fmt.Sprintf("%v", this.ISIS), "ISISLinkParameters", "v1alpha1.ISISLinkParameters", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TopologyList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]Topology{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "Topology", "Topology", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&TopologyList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *TopologyNode) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TopologyNode{`,
		`Name:` + valueToStringGenerated(this.Name) + `,`,
		`Region:` + valueToStringGenerated(this.Region) + `,`,
		`Site:` + valueToStringGenerated(this.Site) + `,`,
		`Rack:` + valueToStringGenerated(this.Rack) + `,`,
		`Position:` + valueToStringGenerated(this.Position) + `,`,
		`UserDefinedLabels:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.UserDefinedLabels), "UserDefinedLabels", "v1alpha11.UserDefinedLabels", 1), `&`, ``, 1) + `,`,
		`Location:` + strings.Replace(fmt.Sprintf("%v", this.Location), "Location", "v1alpha12.Location", 1) + `,`,
		`Provider:` + valueToStringGenerated(this.Provider) + `,`,
		`PlatformType:` + valueToStringGenerated(this.PlatformType) + `,`,
		`Version:` + valueToStringGenerated(this.Version) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TopologySpec) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForNodes := "[]*TopologyNode{"
	for _, f := range this.Nodes {
		repeatedStringForNodes += strings.Replace(f.String(), "TopologyNode", "TopologyNode", 1) + ","
	}
	repeatedStringForNodes += "}"
	repeatedStringForLinks := "[]*TopologyLink{"
	for _, f := range this.Links {
		repeatedStringForLinks += strings.Replace(f.String(), "TopologyLink", "TopologyLink", 1) + ","
	}
	repeatedStringForLinks += "}"
	s := strings.Join([]string{`&TopologySpec{`,
		`Defaults:` + strings.Replace(this.Defaults.String(), "TopologyNode", "TopologyNode", 1) + `,`,
		`Nodes:` + repeatedStringForNodes + `,`,
		`Links:` + repeatedStringForLinks + `,`,
		`}`,
	}, "")
	return s
}
func (this *TopologyStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TopologyStatus{`,
		`ConditionedStatus:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ConditionedStatus), "ConditionedStatus", "v1alpha13.ConditionedStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Topology) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Topology: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Topology: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TopologyEndpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TopologyEndpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TopologyEndpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Node = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleBay", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ModuleBay = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Module = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Adaptor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Adaptor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoint", wireType)
			}
			m.Endpoint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Endpoint |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TopologyLink) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TopologyLink: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TopologyLink: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endpoints = append(m.Endpoints, TopologyEndpoint{})
			if err := m.Endpoints[len(m.Endpoints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BFD", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BFD == nil {
				m.BFD = &v1alpha1.BFDLinkParameters{}
			}
			if err := m.BFD.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BGP", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BGP == nil {
				m.BGP = &v1alpha1.BGPLinkParameters{}
			}
			if err := m.BGP.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OSPF", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OSPF == nil {
				m.OSPF = &v1alpha1.OSPFLinkParameters{}
			}
			if err := m.OSPF.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ISIS", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ISIS == nil {
				m.ISIS = &v1alpha1.ISISLinkParameters{}
			}
			if err := m.ISIS.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TopologyList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TopologyList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TopologyList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, Topology{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TopologyNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TopologyNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TopologyNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Name = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Region = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Site", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Site = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rack", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Rack = &s
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Position = &s
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDefinedLabels", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UserDefinedLabels.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Location == nil {
				m.Location = &v1alpha12.Location{}
			}
			if err := m.Location.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Provider = &s
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlatformType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.PlatformType = &s
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Version = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TopologySpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TopologySpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TopologySpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Defaults", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Defaults == nil {
				m.Defaults = &TopologyNode{}
			}
			if err := m.Defaults.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, &TopologyNode{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Links", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Links = append(m.Links, &TopologyLink{})
			if err := m.Links[len(m.Links)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TopologyStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TopologyStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TopologyStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConditionedStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ConditionedStatus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
